export const SAVE_CART_REQUEST = "SAVE_CART_REQUEST";
export const FETCH_CART_REQUEST = "FETCH_CART_REQUEST";
export const UPDATE_CART_REQUEST = "UPDATE_CART_REQUEST";
export const DELETE_CART_REQUEST = "DELETE_CART_REQUEST";
export const CART_SUCCESS = "CART_SUCCESS";
export const CART_FAILURE = "CART_FAILURE";